on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy Bot
        run: |
          env > $HOME/fran4wi-slackbot/.env
          systemctl --user restart slackbot
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_SIGN_SECRET: ${{ secrets.SLACK_SIGN_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JOIN_WS_SHEET_ID: ${{ secrets.JOIN_WS_SHEET_ID }}
          VOLUNTEER_HANDBOOK_LINK: ${{ secrets.VOLUNTEER_HANDBOOK_LINK }}
          NEW_WS_JOINER_REACHOUT_IDS: ${{ secrets.NEW_WS_JOINER_REACHOUT_IDS }}
